Adding metriq qedc blog post.
unitaryfund/unitary.foundation pull request #300
Opened 2023-02-23 11:21 UTC by vprusso

Adding blog post for Metriq <-> QED-C pipeline.

2023-02-23 14:09 UTC, nathanshammah requested changes
Looks great, thanks for the nice additions @vprusso regarding the Python client. You just need to update the index at blog.html and generate the html file from this md with the instructions from the Readme.

2023-02-23 14:09 UTC, nathanshammah commented on posts/_markdown/metriq_qedc.md
> +application-oriented benchmarks that we made public with supporting data along
```suggestion
application-oriented benchmarks that were made public with supporting data along
```

2023-02-23 17:42 UTC, willzeng commented on posts/_markdown/metriq_qedc.md
> +([QED-C](https://quantumconsortium.org/)) into **Metriq**, the open platform that
Should be a hyperlink to metriq!

2023-02-23 17:43 UTC, willzeng commented
Made one small comment but this looks great to ship from me!

2023-02-23 17:46 UTC, vprusso commented
> d91beb9

Covered in [d91beb9](https://github.com/unitaryfund/unitary-fund/pull/300/commits/d91beb9e7e3502f1c5404cecde93a1e1c607b32f)

2023-02-23 17:46 UTC, vprusso commented
> Made one small comment but this looks great to ship from me!

Covered in [d91beb9](https://github.com/unitaryfund/unitary-fund/pull/300/commits/d91beb9e7e3502f1c5404cecde93a1e1c607b32f)

2023-02-23 17:46 UTC, vprusso commented
Addressed comments from @natestemen in [d91beb9](https://github.com/unitaryfund/unitary-fund/pull/300/commits/d91beb9e7e3502f1c5404cecde93a1e1c607b32f)

2023-02-23 18:16 UTC, nathanshammah commented
@vprusso one small thing we missed: Can you please change the files names to 2023_metriq_qedc as it's our current format? Thanks.

2023-02-23 18:33 UTC, WrathfulSpatula commented on posts/metriq_qedc.html
> +                                <p>The Technical Advisory Committee (TAC) for Standards and Performance Metrics from QED-C provided an open-source suite of quantum benchmarks (<a href="https://github
Same comment as above: m dash (—)

2023-02-23 18:34 UTC, WrathfulSpatula commented on posts/_markdown/metriq_qedc.md
> +with a preprint–an incredibly valuable asset to the benchmarking community.
Alternatively, just make it a comma to indicate a parenthetical phrase.

2023-02-24 00:16 UTC, vprusso commented on posts/_markdown/metriq_qedc.md
> +with a preprint–an incredibly valuable asset to the benchmarking community.
I loved this comment--great attention to detail! Fixed in [568509d](https://github.com/unitaryfund/unitary-fund/pull/300/commits/568509d2de2f168229634c6bd0eff87385a67a23)

2023-02-24 00:16 UTC, vprusso commented
Updated and responded to all comments: [568509d](https://github.com/unitaryfund/unitary-fund/pull/300/commits/568509d2de2f168229634c6bd0eff87385a67a23)

2023-02-28 15:35 UTC, nathanshammah approved these changes

2023-02-28 15:35 UTC, nathanshammah commented on blog.html
> +                    <span class="blog-post-date">23 February, 2023</span>
```suggestion
                    <span class="blog-post-date">28 February, 2023</span>
```

2023-02-28 15:35 UTC, nathanshammah commented on posts/2023_metriq_qedc.html
> +    <meta name="date" content='2023-02-23'>
```suggestion
    <meta name="date" content='2023-02-28'>
```

2023-02-28 15:35 UTC, nathanshammah commented on posts/2023_metriq_qedc.html
> +                            2023-02-23
```suggestion
                            2023-02-28
```

2023-02-28 15:36 UTC, vprusso commented
Awesome. Thank you for the updates, @nathanshammah !

2023-02-28 15:37 UTC, vprusso commented
MWR! 🚀

2023-02-28 15:37 UTC, merged